const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const core = require('../assets/heard-core.js');
const now = 2000000000000;
assert.equal(core.age(now / 1000, now), 'now');
assert.equal(core.age(now / 1000 - 900, now), '15m');
assert.equal(core.age(now / 1000 - 10800, now), '3h');
assert.equal(core.age(now / 1000 - 86400, now), '1d');
const data = {version: 1, published_at: now/1000, nodes: [{name: '<svg onload=alert(1)>', position: [43,-79]}], messages: [{name:'Visitor',text:'<script>bad</script>',received_at:now/1000}]};
assert.equal(core.validate(data), data);
assert.throws(() => core.validate({...data, nodes: [{name:'Invalid',position:[Infinity,0]}]}));
assert.throws(() => core.validate({...data, nodes: [{name:'Invalid',position:[91,0]}]}));
assert.throws(() => core.validate({...data, messages: [{name:'Invalid',text:'Hello',received_at:null}]}));
assert.equal(core.color('Peer'), core.color('PEER'));
const code = fs.readFileSync(path.join(__dirname,'../assets/heard.js'),'utf8');
assert.doesNotMatch(code, /innerHTML|outerHTML|insertAdjacentHTML|geolocation|\/api\/|127\.0\.0\.1/);
const exported = core.validate(JSON.parse(fs.readFileSync(path.join(__dirname,'../data/heard.json'))));
assert.deepEqual(Object.keys(exported).sort(), ['version','published_at','nodes','messages'].sort());
for (const n of exported.nodes) assert.deepEqual(Object.keys(n).sort(), ['name','position']);
for (const m of exported.messages) assert.deepEqual(Object.keys(m).sort(), ['name','received_at','text']);
console.log('Passed public snapshot schema, time labels, invalid-data handling, safe text rendering and same-origin read-only feed checks.');
