const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const core = require('../assets/heard-core.js');
const now = 2000000000000;
assert.equal(core.age(now / 1000, now), 'now');
assert.equal(core.age(now / 1000 - 900, now), '15m');
assert.equal(core.age(now / 1000 - 10800, now), '3h');
assert.equal(core.age(now / 1000 - 86400, now), '1d');
const data = {version: 1, published_at: now/1000, nodes: [{name: '<svg onload=alert(1)>', position: [43,-79]}], messages: [{name:'Visitor',text:'<script>bad</script>',received_at:now/1000}]};
assert.equal(core.validate(data), data);
assert.throws(() => core.validate({...data, nodes: [{name:'Invalid',position:[Infinity,0]}]}));
assert.throws(() => core.validate({...data, nodes: [{name:'Invalid',position:[91,0]}]}));
assert.throws(() => core.validate({...data, messages: [{name:'Invalid',text:'Hello',received_at:null}]}));
assert.equal(core.color('Peer'), core.color('PEER'));
const code = fs.readFileSync(path.join(__dirname,'../assets/heard.js'),'utf8');
assert.doesNotMatch(code, /innerHTML|outerHTML|insertAdjacentHTML|geolocation|\/api\/|127\.0\.0\.1/);
const exported = core.validate(JSON.parse(fs.readFileSync(path.join(__dirname,'../data/heard.json'))));
assert.deepEqual(Object.keys(exported).sort(), ['version','published_at','nodes','messages','activity','arrivals','locations'].sort());
for (const n of exported.nodes) assert.deepEqual(Object.keys(n).sort(), ['name','position']);
for (const m of exported.messages) assert.deepEqual(Object.keys(m).sort(), ['name','received_at','text']);
for (const a of exported.arrivals) assert.deepEqual(Object.keys(a).sort(), ['first_seen','name','position']);
assert.deepEqual(Object.keys(exported.activity).sort(), ['hours','since','through']);
assert.deepEqual(Object.keys(exported.locations).sort(), ['mapped','unknown']);
const hour = stamp => Date.parse(stamp) / 1000;
const through = hour('2026-09-16T16:00:00Z');
const activity = {since:through-3600, through, hours:[[through-3600,4],[through,3]]};
const hourly = core.activityBins(activity,'24h');
assert.equal(hourly.length,24);
assert.equal(hourly.filter(b=>b.known).length,2);
assert.equal(hourly.at(-1).count,3);
assert.equal(hourly.at(-1).partial,true);
assert.equal(core.activityBins(activity,'7d').reduce((s,b)=>s+b.count,0),7);
assert.equal(core.activityBins(activity,'30d').length,30);
assert.equal(core.activityBins({since:null,through,hours:[]},'7d').some(b=>b.known),false);
// Both occurrences of 1am on Toronto's fall-back day belong to the same day.
const fallBack = {since:hour('2026-11-01T05:00:00Z'), through:hour('2026-11-02T17:00:00Z'),
  hours:[[hour('2026-11-01T05:00:00Z'),2],[hour('2026-11-01T06:00:00Z'),3],[hour('2026-11-02T17:00:00Z'),7]]};
const fallDays = core.activityBins(fallBack,'7d');
assert.equal(fallDays.at(-2).count,5);
assert.equal(fallDays.at(-1).count,7);
assert.throws(()=>core.validate({...data, activity:{since:through,through,hours:[[through,-1]]}}));
assert.throws(()=>core.validate({...data, activity:{since:through,through,hours:[[through,1],[through,2]]}}));
assert.throws(()=>core.validate({...data, arrivals:[{name:'Private',position:[43,-79],first_seen:through}]}));
assert.throws(()=>core.validate({...data, locations:{mapped:99,unknown:1}}));
console.log('Passed public snapshot schema, time labels, invalid-data handling, safe text rendering and same-origin read-only feed checks.');
